<?php

namespace App\Filament\Resources\CompanyResource\Pages;

use App\Filament\Resources\CompanyResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;

class CreateCompany extends CreateRecord
{
    protected static string $resource = CompanyResource::class;
    protected static ?string $navigationLabel = 'Create Company Profile';
    protected function onValidationError(\Illuminate\Validation\ValidationException $exception): void
    {
        Notification::make()
            ->title($exception->getMessage())
            ->danger()
            ->send();
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // Check if property is exists or not
        if (array_key_exists('is_claimed', $data) && $data['is_claimed'] == 'on') {
            $data['is_claimed'] = true;
        }

        // if its true, then change the company owner to the claimed_by user
        if ($data['is_claimed']) {
            $data['user_id'] = $data['claimed_by'];
        } else {
            $data['claimed_by'] = null;
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
