<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Actions;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Validation\ValidationException;

class EditUser extends EditRecord
{
    protected static string $resource = UserResource::class;

    protected function onValidationError(ValidationException $exception): void
    {
        Notification::make()
            ->title($exception->getMessage())
            ->danger()
            ->send();
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {

        // Check if property is exists or not
        if (array_key_exists('is_verified', $data) && $data['is_verified'] == 'on') {
            $data['is_verified'] = true;
        } else {
            $data['is_verified'] = false;
        }

        // if its true, then change the company owner to the claimed_by user
        if ($data['is_verified']) {
            $data['email_verified_at'] = now();
        } else {
            $data['email_verified_at'] = null;
        }

        // unset the is_verified key from the array
        unset($data['is_verified']);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
