name: Deploy to bisdir.hkdevs.tech

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Connect to VPS and deploy code
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hkdevs-bisdir/htdocs/bisdir.hkdevs.tech/
            git fetch origin main
            git pull origin main
            echo "Done"
