name: Deploy to bisdir.hkdevs.tech

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Connect to VPS and deploy code
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hkdevs-bisdir/htdocs/bisdir.hkdevs.tech/
            git checkout main
            git fetch origin main
            git pull origin main
            composer install
            npm install
            chmod -R 775 storage
            chmod -R ugo+rw storage
            chown -R www-data.www-data storage
            chown -R www-data.www-data bootstrap/cache
            php artisan config:cache
            php artisan migrate --force
            php artisan storage:unlink
            php artisan storage:link
            git checkout pipeline
            git add .
            git commit -m "Deployed from Github Action"
            git push origin pipeline
            git checkout main
            echo "Done"
