name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Do nothing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Hello World"
            ls -al
            pwd
            whoami
            echo "Done"
