name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest

    steps:
      - name: Do nothing
        uses: appleboy/ssh-actions@v0.1.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git fetch origin main
            git pull origin main
            echo "Done"
