name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: self-hosted

    steps:
    - name: Do nothing
      run: echo "This workflow does nothing."
