name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        run: |
          ssh root@68.183.103.93 "cd /home/bisdir/htdocs/bisdir.hkdevs.tech/ && git pull origin main"
        env:
          VPS_IP: 68.183.103.93
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash
